apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-playground-deployment
  labels:
    app: aks-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-playground
  template:
    metadata:
      labels:
        app: aks-playground
    spec:
      containers:
      - name: sampleapp
        image: docker.io/bbachin1/sample-aks-image
        # volumeMounts:
        #   - mountPath: "/usr/share/nginx/html"
        #     name: task-pv-storage
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      # volumes:
      #   - name: task-pv-storage
      #     persistentVolumeClaim:
      #       claimName: aks-playground
---
apiVersion: v1
kind: Service
metadata:
  name: aks-playground-service
  labels:
    app: aks-playground
spec:
  type: LoadBalancer
  selector:
    app: aks-playground
  ports:
  - port: 80
